#!/usr/bin/env python3
"""
visualize_graph.py
------------------

This script visualizes the output of 'filtered_outputs.py'.

It performs the following steps:
1.  Loads the filtered adjacency matrix (filtered_adjacency_matrix.npy).
2.  Loads the filtered metadata (filtered_metadata.csv) to get (x, y) coordinates and original indices.
3.  Creates a graph from the matrix using NetworkX.
4.  Uses the (x, y) coordinates as the node layout.
5.  Uses the original 'index' from the CSV as node labels.
6.  Draws and saves the final topological map.

Usage:
  python scripts/test/visualize_graph.py \
      --matrix_path results/run/adjacency_matrix.npy \
      --metadata_csv filtered_results/filtered_metadata.csv \
      --output_png results/run/coordinate_map_visualization.png
"""

import argparse
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------
# Check dependencies
# ---------------------------------------------------------------
try:
    import matplotlib.pyplot as plt
    import networkx as nx
    import numpy as np
    import pandas as pd
except ImportError as e:
    print(f"[ERROR] Missing necessary libraries: {e}", file=sys.stderr)
    print("Please run: pip install matplotlib networkx numpy pandas", file=sys.stderr)
    sys.exit(1)

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Visualize the filtered topological map."
    )
    
    parser.add_argument(
        "--matrix_path", 
        type=str, 
        required=True,
        help="[Input] Path to the filtered 'filtered_adjacency_matrix.npy' file."
    )
    parser.add_argument(
        "--metadata_csv", 
        type=str, 
        required=True,
        help="[Input] Path to the filtered 'filtered_metadata.csv' file (for coordinates and labels)."
    )
    parser.add_argument(
        "--output_png", 
        type=str, 
        default="filtered_results/coordinate_map_visualization.png",
        help="[Output] Path to save the visualization .png image."
    )
    parser.add_argument(
        "--figure_size", 
        type=int, 
        default=20,
        help="Size of the generated image (square, in inches)."
    )
    
    return parser.parse_args()

def main():
    args = parse_args()
    
    # --- 1. Load data ---
    print("--- 1. Loading filtered data ---")
    try:
        adj_matrix = np.load(args.matrix_path)
    except FileNotFoundError:
        print(f"[ERROR] Matrix file not found: {args.matrix_path}", file=sys.stderr)
        sys.exit(1)
        
    try:
        df = pd.read_csv(args.metadata_csv)
    except FileNotFoundError:
        print(f"[ERROR] Metadata CSV not found: {args.metadata_csv}", file=sys.stderr)
        sys.exit(1)

    # --- 2. Validate data ---
    M_matrix = adj_matrix.shape[0]
    M_csv = len(df)
    
    if M_matrix != M_csv:
        print(f"[ERROR] Data mismatch!", file=sys.stderr)
        print(f"  Matrix has {M_matrix} nodes, but CSV has {M_csv} rows.", file=sys.stderr)
        print("  Please ensure you are using the corresponding files generated by 'filter_outputs.py'.", file=sys.stderr)
        sys.exit(1)
        
    if not all(col in df.columns for col in ['index', 'x', 'y']):
        print(f"[ERROR] CSV file is missing 'index', 'x', 'y' columns.", file=sys.stderr)
        sys.exit(1)
        
    print(f"Load successful. Ready to visualize {M_matrix} nodes.")

    # --- 3. Build graph and layout ---
    print("--- 2. Building NetworkX graph and layout ---")
    
    # Create graph from adjacency matrix
    # Nodes will be automatically labeled 0, 1, 2, ..., M-1
    G = nx.from_numpy_array(adj_matrix)
    # Remove all self-loops (edges from a node to itself) so they are not drawn
    G.remove_edges_from(nx.selfloop_edges(G))
    
    # Key step:
    # We need to map the nodes in the graph (0 to M-1) to their (x, y) coordinates and 'index' labels.
    # Since the row order of 'filtered_metadata.csv' matches the matrix index order,
    # we can directly use the DataFrame's index (0 to M-1) for mapping.
    
    # a. Create position dictionary: {node_id: (x, y)}
    #    e.g., {0: (6.55, -0.63), 1: (6.55, 1.19), 2: (30.40, -9.93), ...}
    pos_df = df[['x', 'y']]
    pos = pos_df.apply(tuple, axis=1).to_dict()
    
    # b. Create label dictionary: {node_id: 'label'}
    #    e.g., {0: '0', 1: '3', 2: '6', ...}
    label_df = df['index'].astype(str) # Ensure labels are strings
    labels = label_df.to_dict()

    print(f"Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges.")

    # --- 4. Plotting ---
    print(f"--- 3. Starting to plot (may take some time) ---")
    
    plt.figure(figsize=(args.figure_size, args.figure_size))
    
    # 1. Draw nodes
    nx.draw_networkx_nodes(
        G,
        pos=pos,          # Use (x, y) coordinate layout
        node_size=100,     # Node size
        node_color='skyblue',
        alpha=0.8,
        edgecolors='black',
        linewidths=0.5
    )
    
    # 2. Draw edges
    nx.draw_networkx_edges(
        G,
        pos=pos,          # Edges also connect to (x, y) coordinates
        edge_color='gray',
        width=0.7,
        alpha=0.5
    )
    
    # 3. Draw labels
    nx.draw_networkx_labels(
        G,
        pos=pos,
        labels=labels,    # Use original 'index' as labels
        font_size=8,
        font_color='black',
        font_weight='bold'
    )
    
    plt.title(f"Topological Map by Coordinate Distribution (N={G.number_of_nodes()}, Edges={G.number_of_edges()})", fontsize=20)
    plt.xlabel("X Coordinate", fontsize=14)
    plt.ylabel("Y Coordinate", fontsize=14)
    
    # Ensure X and Y axes have the same scale, otherwise the spatial layout will be distorted
    plt.axis('equal')
    plt.grid(True, linestyle='--', alpha=0.6) # Add grid for better visualization

    # --- 5. Save image ---
    output_file = Path(args.output_png)
    # Ensure the output directory exists
    os.makedirs(output_file.parent, exist_ok=True)
    
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"--- 4. Done ---")
    print(f"Visualization image saved to: {output_file}")


if __name__ == "__main__":
    main()