#!/usr/bin/env python3
"""
scripts/compare/compute_distance_matrix.py
----------------

Offline pairwise distance/similarity matrix computation. Reads a .npy file of
feature vectors (e.g., as generated by encode_images.py) and computes the
full pairwise matrix using L2 (Euclidean) distance, Cosine Distance,
or Cosine Similarity.

This script generates one file:
  - <out_matrix>: (float32, shape [N, N]) The pairwise values,
                    where N is the number of input feature vectors.

Usage:
  # Example for L2 Distance (default)
  python scripts/compare/compute_distance_matrix.py \
      --features tmp/run/data_features.npy \
      --out_matrix tmp/run/l2_distances.npy \
      --metric l2

  # Example for Cosine Distance
  python scripts/compare/compute_distance_matrix.py \
      --features tmp/dino_features.npy \
      --out_matrix tmp/dino_cos_dis.npy \
      --metric cos_dis \
      --batch_size 512

  # Example for Cosine Similarity
  python scripts/compare/compute_distance_matrix.py \
      --features tmp/dino_features.npy \
      --out_matrix tmp/dino_cos_sim.npy \
      --metric cos_sim \
      --batch_size 512
"""

import argparse
import sys
import time
from pathlib import Path
from typing import List, Tuple, Optional

import numpy as np
import torch

# Attempt to import tqdm for progress bar
try:
    from tqdm import tqdm
    TQDM_AVAILABLE = True
except ImportError:
    TQDM_AVAILABLE = False


# ----------------------------------------------------------------------------
#                       ARGUMENT PARSING
# ----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parses command-line arguments for the computation script.

    Returns:
        argparse.Namespace: The populated namespace with arguments.
    """
    ap = argparse.ArgumentParser(
        description="Offline Pairwise Matrix Computation (L2, Cosine Distance, or Cosine Similarity)."
    )

    # --- Input Configuration ---
    default_tmp_dir = Path("./tmp/run")
    default_feat_name = "data_features.npy"
    default_dist_name = "matrix.npy"

    ap.add_argument(
        "--features",
        type=str,
        default=str(default_tmp_dir / default_feat_name),
        help=f"Path to input features.npy file. Default: {default_tmp_dir / default_feat_name}"
    )

    # --- Output Configuration ---
    ap.add_argument(
        "--out_matrix",
        type=str,
        default=str(default_tmp_dir / default_dist_name),
        help=f"Path to save output .npy file. Suggest naming based on metric (e.g., 'l2_dist.npy'). Default: {default_tmp_dir / default_dist_name}"
    )

    # --- Computation Configuration ---
    ap.add_argument(
        "--metric",
        type=str,
        default="l2",
        choices=["l2", "cos_dis", "cos_sim"],
        help="Metric to use. 'l2' for Euclidean, 'cos_dis' for Cosine Distance (1 - sim), 'cos_sim' for Cosine Similarity. Default: l2"
    )
    ap.add_argument(
        "--batch_size",
        type=int,
        default=1024,
        help="Batch size for computation. Reduce if OOM (out of memory). Default: 1024"
    )
    ap.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Device to use. 'auto' prefers GPU if available. Default: auto"
    )

    args = ap.parse_args()

    # Ensure output directory exists before starting.
    Path(args.out_matrix).parent.mkdir(parents=True, exist_ok=True)
    
    # Ensure input file exists
    if not Path(args.features).is_file():
        print(
            f"ERROR: Input feature file not found: {args.features}",
            file=sys.stderr
        )
        sys.exit(1)

    return args


# ----------------------------------------------------------------------------
#                       CORE COMPUTATION
# ----------------------------------------------------------------------------

def compute_distance_matrix(
    feats_np: np.ndarray,
    device: torch.device,
    metric: str = "l2",
    batch_size: int = 1024
) -> np.ndarray:
    """Computes the pairwise distance/similarity matrix in batches.
    
    Args:
        feats_np: A numpy array of shape [N, D] (float32).
        device: The torch.device (CPU or CUDA) to use for computation.
        metric: The metric ("l2", "cos_dis", or "cos_sim").
        batch_size: The number of rows to compute at a time.

    Returns:
        np.ndarray: A float32 array of shape [N, N] containing distances
        or similarities.
    """
    N, D = feats_np.shape
    print(f"Input features shape: ({N}, {D})")
    
    # Move all features to the target device.
    # This is usually fine as [N, D] is much smaller than [N, N].
    try:
        feats_all_device = torch.from_numpy(feats_np).to(device)
    except Exception as e:
        print(f"ERROR: Failed to move features to device '{device}'.", file=sys.stderr)
        print(f"This often means the features ({N}x{D}) won't fit in VRAM.", file=sys.stderr)
        print(f"Error details: {e}", file=sys.stderr)
        sys.exit(1)

    # --- Pre-computation based on metric ---
    # For Cosine metrics, we pre-normalize the "database" side.
    # The "query" side will be normalized in batches.
    if metric in ("cos_dis", "cos_sim"):
        print("Pre-normalizing features for Cosine metric...")
        feats_all_device_db = torch.nn.functional.normalize(
            feats_all_device, p=2, dim=1
        )
    else:
        # For L2, the database is just the original tensor
        feats_all_device_db = feats_all_device
    # -------------------------------------

    all_row_batches = []
    
    print(f"Computing [N, N] {metric.upper()} matrix with N={N} using batch size {batch_size}...")

    # Set up progress bar if tqdm is available
    num_batches = (N + batch_size - 1) // batch_size
    desc = f"[Compute {metric.upper()}]"
    if TQDM_AVAILABLE:
        iterable = tqdm(
            range(0, N, batch_size),
            desc=desc,
            unit="batch",
            total=num_batches
        )
    else:
        iterable = range(0, N, batch_size)

    # Disable gradient computation for efficiency
    with torch.no_grad():
        for i, start_idx in enumerate(iterable):
            end_idx = min(start_idx + batch_size, N)
            
            # Get the query batch (this is just a view, no memory copy)
            # We always slice from the *original* feature tensor
            feats_batch_device = feats_all_device[start_idx:end_idx, :]
            
            if metric == "l2":
                # Compute L2 distances: (batch_size, N)
                # torch.cdist computes p-norm, p=2.0 is L2
                matrix_batch = torch.cdist(
                    feats_batch_device, feats_all_device_db, p=2.0
                )
            
            elif metric in ("cos_dis", "cos_sim"):
                # 1. Normalize the current query batch
                feats_batch_norm = torch.nn.functional.normalize(
                    feats_batch_device, p=2, dim=1
                )
                
                # 2. Compute similarity: (B, D) @ (D, N) -> (B, N)
                #    We matmul the normalized batch with the pre-normalized database
                sim_batch = torch.matmul(feats_batch_norm, feats_all_device_db.T)
                
                if metric == "cos_dis":
                    # 3. Compute Cosine Distance = 1 - Cosine Similarity
                    matrix_batch = 1.0 - sim_batch
                    # 4. Clamp values to [0, 2] for numerical stability
                    matrix_batch = torch.clamp(matrix_batch, 0.0, 2.0)
                else: # metric == "cos_sim"
                    # 3. Use similarity directly
                    matrix_batch = sim_batch
                    # 4. Clamp values to [-1, 1] for numerical stability
                    matrix_batch = torch.clamp(matrix_batch, -1.0, 1.0)
                
            else:
                # This should not be reachable due to argparse 'choices'
                raise ValueError(f"Unknown metric: {metric}")

            # Move the computed batch of rows to CPU to free VRAM
            all_row_batches.append(matrix_batch.cpu())

            if not TQDM_AVAILABLE and (i % 20 == 0):
                print(f"[Compute] Processed batch {i}/{num_batches}")

    # Concatenate all CPU tensors
    print("Concatenating batch results...")
    full_matrix = torch.cat(all_row_batches, dim=0)
    
    # Convert to NumPy
    return full_matrix.numpy().astype("float32")


# ----------------------------------------------------------------------------
#                       SCRIPT EXECUTION
# ----------------------------------------------------------------------------

def main():
    """Main execution function."""
    args = parse_args()

    # --- 1. Set Device ---
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)
    print(f"Using device: {device}")
    print(f"Using metric: {args.metric.upper()}")

    # --- 2. Load Features ---
    print(f"Loading features from: {args.features}")
    try:
        features_np = np.load(args.features)
        if not features_np.dtype == np.float32:
            print(f"WARN: Converting features from {features_np.dtype} to float32.")
            features_np = features_np.astype(np.float32)
            
        if features_np.ndim != 2:
            print(f"ERROR: Input features must be 2D (N, D), but got shape {features_np.shape}", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        print(f"ERROR: Failed to load features from {args.features}", file=sys.stderr)
        print(f"Error details: {e}", file=sys.stderr)
        sys.exit(1)
        
    N = features_np.shape[0]
    print(f"Loaded {N} vectors of dim {features_np.shape[1]}")

    # --- 3. Compute Distance Matrix ---
    t0 = time.time()
    
    dist_matrix = compute_distance_matrix(
        features_np,
        device,
        args.metric,
        args.batch_size
    )
    
    dt = time.time() - t0

    # --- 4. Handle Results ---
    print("\n--- Computation Complete ---")
    print(f"Successfully computed {args.metric.upper()} matrix.")
    print(f"Output shape: {dist_matrix.shape}")
    print(f"Total time: {dt:.2f}s")
    
    # Simple sanity check
    if not dist_matrix.shape == (N, N):
          print(f"ERROR: Final matrix shape {dist_matrix.shape} does not match expected ({N}, {N})", file=sys.stderr)
          sys.exit(1)

    # --- 5. Save Results ---
    print(f"Saving matrix to: {args.out_matrix}")
    try:
        np.save(args.out_matrix, dist_matrix)
    except Exception as e:
        print(f"ERROR: Failed to save matrix to {args.out_matrix}", file=sys.stderr)
        print(f"Error details: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Saved matrix to: {args.out_matrix}")
    print("Done.")


if __name__ == "__main__":
    main()